version: "3.9"
services:
  myapp:
    environment:
      JEKYLL_UID: 1000
      JEKYLL_GID: 1000
      JEKYLL_ENV: production
    build: .
    ports: 
      - "2222:2222"
    # image: myapp
    image: 192.168.1.10:5000/clusteredpi
    restart: always
    volumes:
      - /home/pi/ClusteredPi/certbot/conf:/etc/certbot:ro
      - /home/pi/ClusteredPi/certbot/data:/var/www/certbot:ro