version: "3.9"
services:
  myapp:
    environment:
      JEKYLL_UID: 1000
      JEKYLL_GID: 1000
      JEKYLL_ENV: production
    image: 192.168.1.219:5000/my-registry/kevsrobots_myapp  ## goes to local registry
    restart: always
    ports: 
      - "3333:3333"
