version: '3.8'

services:
  db:
    image: linuxserver/mariadb:arm32v7-latest
    container_name: nextcloud_db
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_PASSWORD=your_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  app:
    image: nextcloud:latest
    container_name: nextcloud_app
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud_data:/var/www/html
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=your_password
      - MYSQL_HOST=db

volumes:
  db_data:
  nextcloud_data:
