services:
  kevsrobots:
    environment:
      JEKYLL_UID: 1000
      JEKYLL_GID: 1000
      JEKYLL_ENV: production
    build: .
    image: 192.168.2.1:5000/kevsrobots:latest  ## goes to local registry
    ports: 
      - "3333:3333"
    restart: always
    