version: "3.9"
services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports: 
      - "11434:11434"
    
    restart: always
    volumes:
      - /home/pi/ollama:/root/.ollama
  ollama-webiu:
    build:
      context: ./webui
      args:
        OLLAMA_API_BASE_URL: '/ollama/api'
      dockerfile: Dockerfile
    image: ghcr.io/ollama/ollama-webui:main
    container_name: ollama-webui
    volumes:
      - ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    restart: unless-stopped
volumes:
  ollama-webui: {}
  ollama: {}