version: '3.8'

services:
  crate:
    image: crate
    environment:
      - CRATE_HEAP_SIZE=1g
      - CRATE_CLUSTER_NAME=my_cluster
      - network.host=0.0.0.0
      - network.publish_host=${HOSTNAME}            # Dynamically assign host name
      - transport.publish_port=4300
      - discovery.seed_hosts=tasks.crate:4300       # Use Docker Swarm's internal DNS
      - cluster.initial_master_nodes=tasks.crate    # Set initial master nodes
    ports:
      - "4200:4200"
      - "5432:5432"
      - "4300:4300"
    volumes:
      - crate-data:/data
    networks:
      - crate-network
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1  # Ensures one replica per host

volumes:
  crate-data:

networks:
  crate-network:
    driver: overlay
