services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/kev/ClusteredPi/home_assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true

    networks:
      mymacvlanActive:
        ipv4_address: 192.168.1.150
    environment:
      - DISABLE_JEMALLOC=true
networks:
  mymacvlanActive:
    driver: macvlan
    driver_opts:
      parent: eth0 # Replace with your interface
    ipam:
      config:
        - subnet: 192.168.1.0/24 # Replace with your subnet
          gateway: 192.168.1.254 # Replace with your gateway
    