version: '3'
services:
  mosquitto:
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - /home/pi/ClusteredPi/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /home/pi/ClusteredPi/config/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
      - /home/pi/ClusteredPi/config/log/mosquitto.log:/mosquitto/log/mosquitto.log
      - /home/pi/ClusteredPi/config/data:/mosquitto/data
    ports:
      - "1883:1883"
    networks:
      mymacvlanActive:
        ipv4_address: 192.168.1.152
       
networks:
  mymacvlanActive:
    external: true
    