version: '3'
services:
  mosquitto:
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - /home/kev/ClusteredPi/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /home/kev/ClusteredPi/config/accesscontrollist:/mosquitto/config/accesscontrollist
      - /home/kev/ClusteredPi/config/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
      - /home/kev/ClusteredPi/config/log/mosquitto.log:/mosquitto/log/mosquitto.log
      - /home/kev/ClusteredPi/config/data:/mosquitto/data
    ports:
      - "1883:1883"
    networks:
      mymacvlanActive:
        ipv4_address: 192.168.1.152

networks:
  mymacvlanActive:
    driver: macvlan
    driver_opts:
      parent: eth0  # Change this to the appropriate network interface
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1