services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_PORT: 5433
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    command: /bin/bash -c "mkdir -p /var/lib/postgresql/data && exec docker-entrypoint.sh postgres"
