services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: /bin/bash -c "mkdir -p /var/lib/postgresql/data && exec docker-entrypoint.sh postgres"
