version: "3.9"
services:
  myapp_load_balancer:
    build: .
    ports: 
      - "80:80"
      - "8080:8080"
      - "443:443"
    # image: myapp
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot