services:
  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    restart: always
    networks:
      - monitoring_net
    hostname: $(HOSTNAME)
    environment:
      - HOSTNAME: ${HOSTNAME}
    env_file: ".env"
networks:
  monitoring_net:
    driver: bridge
  