services:
  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    restart: always
    networks:
      - monitoring_net
    environment:
      - HOSTNAME=$(HOSTNAME)
      - hostname=$(HOSTNAME)
networks:
  monitoring_net:
    driver: bridge
  