version: '3.8'
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - monitoring_net
    restart: always  # Automatically restart the container


networks:
  monitoring_net:
    driver: bridge

volumes:
  influxdb_data:
