services:
  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - monitoring_net
    hostname: "${HOSTNAME}"
    environment:
      - HOSTNAME=${HOSTNAME}
    privileged: true
networks:
  monitoring_net:
    driver: bridge
  