services:
  influxdb:
    image: influxdb:1.8  # 1.8 is a known good version
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - influxdb:/var/lib/influxdb
      # - ./influxdb.conf:/etc/influxdb/influxdb.conf
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=kevsrobots
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
volumes:
  influxdb: