services:
  influxdb:
    image: influxdb:latest  # 1.8 is a known good version
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - influxdb:/var/lib/influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf

  influxdb-init:
    image: influxdb
    volumes:
      - influxdb:/var/lib/influxdb
    entrypoint: ["sh", "-c"]
    command: |
      influx -execute "CREATE USER admin WITH PASSWORD 'adminpassword' ADMIN"
      influx -execute "CREATE USER telegraf WITH PASSWORD 'telegrafpassword'"
    depends_on:
      - influxdb
volumes:
  influxdb: