version: "3.9"
services:
  ros2:
    build: .
    restart: always
    ports: 
      - "3332:3332"
    volumes:
      - /home/kev/ros2:/home
      - /home/kev/cubie-1:/ros2
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0