version: '1'
services:
  jekyll-serve:
    image: jekyll/jekyll:4.0
    volumes:
      - '../../web:/srv/jekyll'
    ports:
      - 4000:4000
      - 35729:35729
    command: sh -c "../status.sh && exec jekyll serve --watch --livereload"
