version: '3.3'

services:
  ghost:
    image: ghost:latest
    ports:
      - "2368:2368"
    environment:
      database__client: sqlite3
      database__connection__filename: "/var/lib/ghost/content/data/ghost.db"
      url: http://0.0.0.0:2368
    volumes:
      - ghost_data:/var/lib/ghost/content
    restart: always

volumes:
  ghost_data: