---
- name: Install Home Assistant Node
  hosts: home_assistant
  tasks:
     - name: Install Home Asssistant
       command: "docker run -d --name homeassistant --privileged --restart=unless-stopped -e TZ=Europe/London -v /PATH_TO_YOUR_CONFIG:/config --network=host ghcr.io/home-assistant/home-assistant:stable" 
       ignore_errors: yes