---
- name: Install NodeRed
  hosts: mongo 
  tasks:
     - name: Do not count this as a failure
       ansible.builtin.command: /bin/false
       ignore_errors: yes

     - name: Installing Mongo
       command: "docker run -itd --name mongo -p 27017:27017 -p 28017:28017 mangoraft/mongodb-arm"
       ignore_errors: yes 
