---
- name: Install nginx on lb
  hosts: node01
  tasks:
    
     - name: clone git 
       git:
        repo: 'https://github.com/kevinmcaleer/ClusteredPi'
        dest: /home/pi/ClusteredPi

     - name: Remove old compose
       command: "docker-compose -f /home/pi/ClusteredPi/stacks/nginx/docker-compose.yml rm"
       ignore_errors: yes

     - name: docker-compose build
       command: "docker-compose -f /home/pi/ClusteredPi/stacks/nginx/docker-compose.yml build"
       ignore_errors: yes

     - name: docker-compose up
       command: "docker-compose -f /home/pi/ClusteredPi/stacks/nginx/docker-compose.yml up -d"
       ignore_errors: yes       
     