---
- name: Install nginx on lb
  hosts: node01
  tasks:
    - name: clone git 
      git:
      repo: 'https://github.com/kevinmcaleer/ClusteredPi'
      dest: /home/pi/ClusteredPi
      update: yes

    - name: Stop nginx container
      docker_container:
        name: nginx
        state: stopped

    - name: remove nginx container
      docker_container:
        name: nginx
        state: absent

    #  - name: Remove old compose
    #    command: "docker-compose -f /home/pi/ClusteredPi/stacks/nginx/docker-compose.yml rm"
    #    ignore_errors: yes

    - name: Run `docker-compose up` again
      community.docker.docker_compose:
        project_src: /home/pi/ClusteredPi/stacks/nginx
        build: yes
      register: output

    #  - name: docker-compose build
    #    command: "docker-compose -f /home/pi/ClusteredPi/stacks/nginx/docker-compose.yml build"
    #    ignore_errors: yes

    #  - name: docker-compose up
    #    command: "docker-compose -f /home/pi/ClusteredPi/stacks/nginx/docker-compose.yml up -d"
    #    ignore_errors: yes       
     