---
- name: Install nginx on lb
  hosts: node04
  tasks:
    - name: clone git 
      git:
        repo: 'https://github.com/kevinmcaleer/ClusteredPi'
        dest: /home/pi/ClusteredPi
        update: yes

    - name: Stop nginx container
      docker_container:
        name: nginx_myapp_load_balancer_1
        state: stopped
      ignore_errors: yes  

    - name: remove nginx container
      docker_container:
        name: nginx_myapp_load_balancer_1
        state: absent
        remove_images: all
      ignore_errors: yes  

    - name: Prune everything
      community.docker.docker_prune:
        containers: yes
        images: yes
        networks: yes
        volumes: yes
        builder_cache: yes
      register: output

    - ansible.builtin.debug:
        var: output

    - name: docker-compose build
      command: "docker-compose -f /home/pi/ClusteredPi/stacks/nginx/docker-compose.yml build"
      ignore_errors: yes

    - name: docker-compose up
      command: "docker-compose -f /home/pi/ClusteredPi/stacks/nginx/docker-compose.yml up -d"
      ignore_errors: yes       
     