---
- name: Install `myapp` on Web Nodes
  # hosts: web
  hosts: node03
  tasks:
     - name: clone git 
       git:
         repo: 'https://github.com/kevinmcaleer/ClusteredPi'
         dest: /home/pi/ClusteredPi
         clone: yes
         update: yes
       register: output

     - ansible.builtin.debug:
         var: output
         
     - name: remove myapp container
       community.docker.docker_compose:
        project_src: '/home/pi/ClusteredPi/stacks/jekyll'
        state: absent
        remove_images: all
       register: output
       
     - ansible.builtin.debug:
         var: output

     - name: Prune everything
       community.docker.docker_prune:
         containers: yes
         images: yes
         networks: yes
         volumes: yes
         builder_cache: yes

    #  - name: Create and start services
    #    community.docker.docker_compose:
    #      project_src: /home/pi/ClusteredPi/stacks/jekyll
    #      nocache: yes
    #      recreate: always
    #    register: output

     - ansible.builtin.debug:
         var: output

     - name: Bring myApp up
       community.docker.docker_compose:
         project_src: /home/pi/ClusteredPi/stacks/jekyll
         build: no
         nocache: yes
         recreate: always
         state: present
       register: output
  
     - ansible.builtin.debug:
         var: output