---
- name: Install `myapp` on Web Nodes
  hosts: web
  tasks:
     - name: clone git 
       git:
         repo: 'https://github.com/kevinmcaleer/ClusteredPi'
         dest: /home/pi/ClusteredPi
         clone: yes
         update: yes
       register: output

     - name: remove myapp container
       community.docker.docker_compose:
        project_src: '/home/pi/ClusteredPi/stacks/jekyll'
        state: absent
        nocache: yes
        recreate: always
        remove_images: all
       register: output

     - name: Create and start services
       community.docker.docker_compose:
         project_src: /home/pi/ClusteredPi/stacks/jekyll
       register: output

     - ansible.builtin.debug:
         var: output

     - name: Bring myApp up
       community.docker.docker_compose:
         project_src: /home/pi/ClusteredPi/stacks/jekyll
         build: no
         nocache: yes
         recreate: always
       register: output
  
     - ansible.builtin.debug:
         var: output