---
- name: Install Portainer on Nodes
  hosts: node
  tasks:
     - name: Do not count this as a failure
       ansible.builtin.command: /bin/false
       ignore_errors: yes
     - name: Remove previous version - Stop Container
       command: "docker stop Portainer"
       ignore_errors: yes

     - name: Remove previous version - Remove Container
       command: "docker rm Portainer"
       ignore_errors: yes
